[package]
name = "derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
derive_util = { workspace = true }

proc-macro2 = "1.0.86"
quote = "1.0.37"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
syn = "2.0.77"
